# Generated by Django 5.2.6 on 2026-04-16 01:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Публичный UUID"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, verbose_name="Публичный UUID"
            ),
        ),
    ]
