# Generated by Django 5.2.6 on 2026-04-16 01:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_course_public_id_lesson_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Публичный UUID",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="public_id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Публичный UUID",
            ),
        ),
    ]
