# Generated by Django 5.2.5 on 2026-08-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_quizansweroption_quiz_quizattempt_quizquestion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("upper-intermediate", "Upper-Intermediate"),
                ],
                db_index=True,
                default="beginner",
                max_length=20,
                verbose_name="Уровень урока",
            ),
        ),
    ]
