# Generated by Django 5.2.5 on 2026-07-22 02:36

import django.core.validators
import django.db.models.deletion
import speaking.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0008_quizansweroption_quiz_quizattempt_quizquestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSpeakingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_transcript",
                    models.TextField(verbose_name="Транскрипт материала"),
                ),
                (
                    "reference_summary",
                    models.TextField(verbose_name="Эталонный краткий пересказ"),
                ),
                (
                    "key_points",
                    models.JSONField(
                        help_text='JSON-массив строк, например: ["Main idea", "Important conclusion"]',
                        validators=[speaking.models.validate_key_points],
                        verbose_name="Ключевые мысли",
                    ),
                ),
                (
                    "target_duration_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Целевая длительность, сек.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_config",
                        to="courses.lesson",
                        verbose_name="Урок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка speaking-урока",
                "verbose_name_plural": "Настройки speaking-уроков",
            },
        ),
        migrations.CreateModel(
            name="SpeakingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Публичный UUID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(verbose_name="Номер попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploaded", "Uploaded"),
                            ("transcribing", "Transcribing"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "audio_key",
                    models.CharField(blank=True, max_length=512, verbose_name="S3 key"),
                ),
                (
                    "audio_content_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME-тип аудио"
                    ),
                ),
                (
                    "audio_size_bytes",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Размер аудио, байт"
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, verbose_name="Транскрипт пользователя"
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Длительность, сек."
                    ),
                ),
                (
                    "word_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество слов"
                    ),
                ),
                (
                    "words_per_minute",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Слов в минуту"
                    ),
                ),
                (
                    "filler_word_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Количество слов-паразитов"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Код ошибки"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Описание ошибки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_attempts",
                        to="courses.lesson",
                        verbose_name="Урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaking_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speaking-попытка",
                "verbose_name_plural": "Speaking-попытки",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SpeakingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "meaning_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "compression_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "clarity_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "grammar_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "vocabulary_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "fluency_score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("covered_key_points", models.JSONField(default=list)),
                ("missed_key_points", models.JSONField(default=list)),
                ("unnecessary_details", models.JSONField(default=list)),
                ("corrections", models.JSONField(default=list)),
                ("short_feedback", models.TextField()),
                ("concise_version", models.TextField()),
                ("next_goal", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="speaking.speakingattempt",
                        verbose_name="Попытка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Speaking-feedback",
                "verbose_name_plural": "Speaking-feedback",
            },
        ),
        migrations.AddIndex(
            model_name="speakingattempt",
            index=models.Index(
                fields=["user", "lesson", "created_at"],
                name="speak_user_lesson_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="speakingattempt",
            constraint=models.UniqueConstraint(
                fields=("user", "lesson", "attempt_number"),
                name="unique_speaking_attempt_number_per_user_lesson",
            ),
        ),
    ]
