# Generated by Django 5.2.5 on 2026-08-02 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_lesson_level"),
        ("speaking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="speakingattempt",
            index=models.Index(
                fields=["user", "status", "completed_at"],
                name="speak_user_status_done_idx",
            ),
        ),
    ]
